version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    environment:
      - NEXUS_JDBC_URL=jdbc:postgresql://postgres:5432/nexus
      - NEXUS_JDBC_USER=${POSTGRES_USER}
      - NEXUS_JDBC_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  devops-network:
    external: true
    name: ${NETWORK_NAME}

volumes:
  nexus_data:
    external: true